# bee-check-api


# compose syntax version.
version: "3.6"

# services declaration.
services:
  # PostgreSQL
  postgres:
    image: postgres:10.7
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bee-check
      - POSTGRES_PASSWORD=bee-check
      - POSTGRES_DB=bee-check
    ports:
      - target: 5432
        published: 5432
  # Redis
  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    ports:
      - target: 6379
        published: 6379
  # Web Application
  web:
    image: ambientum/php:7.2-nginx
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=true
      - OPCACHE_MODE=normal
      - PHP_MEMORY_LIMIT=256M
    ports:
      - target: 8080
        published: 8080
      - target: 8083
        published: 8083
    links:
      - postgres
      - redis

# volumes declaration.
volumes:
  # postgres-data
  postgres-data:
    driver: local
  # redis-data
  redis-data:
    driver: local
  # dot-config
  dot-config:
    driver: local
  # dot-cache
  dot-cache:
    driver: local
  # dot-local
  dot-local:
    driver: local
  # dot-composer
  dot-composer:
    driver: local